plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 140
  Exclude:
    - "test/*.rb"

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/MethodParameterName:
  MinNameLength: 2

Naming/VariableNumber:
  EnforcedStyle: normalcase

Metrics/MethodLength:
  Max: 20
