#!/usr/bin/env ruby
# frozen_string_literal: true

require 'slop'
require_relative '../lib/rot135'

def print_version
  puts "rot135 version #{Rot135::VERSION}"
  exit
end

def print_help(options)
  puts options
  exit
end

opts = Slop.parse do |o|
  o.banner = <<~BANNER_END
    usage: #{File.basename $PROGRAM_NAME} [options]"

    rot135 reads its input from STDIN and transforms the read input according to the passed options
  BANNER_END
  o.separator 'Available options:'
  o.bool '-5',  '--five',     'Process decimal digits'
  o.bool '-13', '--thirteen', "Process letters 'a'..'z' & 'A'..'Z' (default)", default: true
  o.bool '-b',  '--both',     'Process decimal digit & ASCII letters (exclusive)'
  o.on   '-v', '--version',   'Print version and exit' do print_version end
  o.on   '-h', '--help', 'Show this help info and exit' do print_help(o) end
end

input = $stdin.read.rstrip

# Option -b is exclusive
if opts.both? && (opts.five? || opts.thirteen?)
  puts "Option '-b', '--both' cannot be combined with -5 or -13"
  exit 1
end

specifiers = []
specifiers << :rot5 if opts.five?
specifiers << :rot13 if opts.thirteen?
specifiers << :rot5 << :rot13 if opts.both?

specifiers << :rot13 if specifiers.empty?

puts Rot135.rot(input, specifiers: specifiers)
